sprav1.0/spravochnik/spravApp/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = "spravApp"
urlpatterns = [
    path('', main, name='main' ),
    path('change/<int:ItemPK>/', mainItemChange, name='mainItemChange' ),
    path('change/<str:ParentTable>/<int:ItemPK>/', change_fk, name='fk_change' ),
    path('<str:ParentTable>/', ParentTable, name='ParentTable' ),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sprav1.0/spravochnik/spravochnik/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('spravApp.urls'))
]

sprav1.0/spravochnik/templates/form.html
{% extends 'index.html' %}

{% block content %}
    <div class="row form" align=center>
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" class="btn btn-primary" value="Сохранить" style="margin-top: 10px">
        </form>
    </div>
{% endblock %}

sprav1.0/spravochnik/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{pageTitle}}</title>
    <link rel="stylesheet" href="{% static 'bootstrap.css'%}">
    <style>
        .form>div>div {
            display: inline-table;
            max-width: 100px;
            margin-right: 20px;
            margin-left: 20px;
            margin-bottom: 20px;
        }
    </style>
</head>

<body>
    {% if error%}
    <script> alert('{{error}}')</script>
    {%endif%}
    {% block content %}
    {% endblock%}
</body>

</html>

sprav1.0/spravochnik/templates/main.html
{% extends 'index.html' %}

{% block content%}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <div class='form' > 
            <div>
                <div>
                    <label for="id">id:</label><br>
                    <input type="text" name="id" class="form-control" style="width: 100px; display:inline-block;" id="id_id">
                </div>
            {{form}}
            </div>
            <div style="self-align:right;margin-bottom: 10px; margin-right: 66px; display: flex; flex-wrap: nowrap; justify-content: space-between; max-width: 50%; justify-content: space-around">
                <input type="submit" name="search" class="btn btn-outline-success" value="Поиск">
                <input type="submit" name="add" class="btn btn-outline-primary" value="Добавить">
                <input type="submit" name="change" class="btn btn-outline-warning" value="Изменить">
                <input type="submit" name="delete" class="btn btn-outline-danger" value="Удалить">
            </div>
        </div>
    </form>

    <table class="table table-bordered">
        <tr class="row text-center" style="flex-wrap: nowrap">
            <th class="col">id</th>
            <th class="col"><a class='link' href="{% url 'spravApp:ParentTable' 'Fam'%}">Фамилия</a></th>
            <th class="col"><a class='link' href="{% url 'spravApp:ParentTable' 'Name'%}">Имя</a></th>
            <th class="col"><a class='link' href="{% url 'spravApp:ParentTable' 'Otc'%}">Отчество</a></th>
            <th class="col"><a class='link' href="{% url 'spravApp:ParentTable' 'Street'%}">Улица</a></th>
            <th class="col">Дом</th>
            <th class="col">Корпус</th>
            <th class="col">Квартира</th>
            <th class="col">Телефон</th>
        </tr>
        {% for MainItem in MainItems %}
        <tr class="row text-center" style="flex-wrap: nowrap">
            <td class="col">{{MainItem.id}}</td>
            <td class="col">{{MainItem.fam}}</td>
            <td class="col">{{MainItem.name}}</td>
            <td class="col">{{MainItem.otc}}</td>
            <td class="col">{{MainItem.street}}</td>
            <td class="col">{{MainItem.bldn}}</td>
            <td class="col">{{MainItem.bldn_k}}</td>
            <td class="col">{{MainItem.appr}}</td>
            <td class="col">{{MainItem.tel}}</td>
        </tr>
        {% endfor %}
    </table> 
</div>
{% endblock %} 

sprav1.0/spravochnik/templates/parentTable.html
{% extends 'index.html' %}

{% block content%}
<a class="btn btn-outline-secondary" href="{% url 'spravApp:main' %}" style="display: inline-block;">Назад</a>
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <div class='form' > 
            <div>
                <div>
                    <label for="id">id:</label><br>
                    <input type="text" name="id" class="form-control" style="width: 100px; display:inline-block;" id="id_id">
                </div>
            {{form}}
            </div>
            <div align="right" style="margin-bottom: 10px; margin-right: 66px">
                <input type="submit" name="search" class="btn btn-outline-success" value="Поиск">
                <input type="submit" name="add" class="btn btn-outline-primary" value="Добавить">
                <input type="submit" name="change" class="btn btn-outline-warning" value="Изменить">
                <input type="submit" name="delete" class="btn btn-outline-danger" value="Удалить">
            </div>
        </div>
    </form>

    <table class="table table-bordered">
        <tr class="row text-center" style="flex-wrap: nowrap">
            <th class="col">id</th>
            <th class="col">{{field}}</th>
        </tr>
        {% for Item in Items %}
        <tr class="row text-center" style="flex-wrap: nowrap">
            <td class="col">{{Item.id}}</td>
            <td class="col">{{Item.val}}</td>
        </tr>
        {% endfor %}
    </table> 
</div>
{% endblock %} 